# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
interests = Interest.create([{interest: 'books'}, {interest: 'camping'},{interest: 'coffee and conversation'},{interest: 'business'},{interest: 'cooking'},{interest: 'dining out'},{interest: 'fishing/hunting'},{interest: 'gardening'},{interest: 'hobbies and crafts'},{interest: 'movies'},{interest: 'museums and art'},{interest: 'music'},{interest: 'exploring'},{interest: 'nightclubs and dancing'},{interest: 'performing arts'},{interest: 'playing cards/board games'},{interest: 'playing sports'},{interest: 'political events'},{interest: 'religion/spirituality'},{interest: 'shopping/antiques'},{interest: 'travel'},{interest: 'video games'},{interest: 'volunteering'},{interest: 'watching sports'},{interest: 'wine tasting'}])
boy1 = User.create({email:'mick@email.com', username:"MasterMick", password:"password", password_confirmation: "password", birthday: 1993/03/24, height: 70, body_type: "average", relationship_status: "widowed", have_children: false, number_children: 0, want_children: "yes", education_level: "Bachelor's", smoker: "No", drinker: "A couple times a week", ethnicity: "White/Caucasian", religion:"atheist", salary:"under $25,000", bio:"HEY! I'm JUST TRYING TO HAVE SUM FUN ;)", zipcode: 60640, personality: "ENFJ", admin_level:1})
boy2 = User.create({email:'curtis@email.com', username:"CurtThaDurt", password:"password", password_confirmation: "password", birthday: 1992/01/19, height: 68, body_type: "average", relationship_status: "divorced", have_children: true, number_children: 3, want_children: "someday", education_level: "Bachelor's", smoker: "Yes", drinker: "No", ethnicity: "Black", religion:"jewish", salary:"$25,000 to $40,000", bio:"HEY! I'm JUST TRYING TO FIND LOVE", zipcode: 60612, personality: "INTP", admin_level:1})
boy3 = User.create({email:'mike@email.com', username:"MikeDrop", password:"password", password_confirmation: "password", birthday: 1988/06/29, height: 70, body_type: "average", relationship_status: "single", have_children: true, number_children: 1, want_children: "yes", education_level: "Bachelor's", smoker: "Yes", drinker: "Every day", ethnicity: "Asian", religion:"jewish", salary:"under $25,000", bio:"HEY! CALL ME", zipcode: 60658, personality: "ISTJ", admin_level:1})
girl1 = User.create({email:'Laura@email.com', username:"LaurOfTheRings", password:"password", password_confirmation: "password", birthday: 1988/06/27, height: 65, body_type: "average", relationship_status: "single", have_children: false, number_children: 0, want_children: "no", education_level: "PHD", smoker: "Yes", drinker: "No", ethnicity: "White/Caucasian", religion:"christian", salary:"under $25,000", bio:"I'm looking for someone to sweep me off my feet", zipcode: 40241, personality: "ESTP", admin_level:0})
girl2 = User.create({email:'Cheryl@email.com', username:"KeepItCheryeal", password:"password", password_confirmation: "password", birthday: 1988/06/27, height: 65, body_type: "average", relationship_status: "single", have_children: false, number_children: 0, want_children: "no", education_level: "PHD", smoker: "Yes", drinker: "No", ethnicity: "White/Caucasian", religion:"christian", salary:"under $25,000", bio:"I'm looking for someone to sweep me off my feet", zipcode: 40241, personality: "ESTP", admin_level:0})
